### ISSUE TITLE
/etc/issue on Fedora contains escape sequence \S

### ISSUE THREAD

**Issue by bluedreamer** [blackducksoftware/ohcount#46]
Fedora uses an escape sequence to insert the OS name into /etc/issue output when processed by agetty
```
[user@localhost ~]$ cat /etc/issue
\S
Kernel \r on an \m (\l)
```
From the agetty man page
```
       s      Insert  the  system  name (the name of the operating system).  Same as `uname -s'.  See also
              the \S escape code.

       S or S{VARIABLE}
              Insert the VARIABLE data from /etc/os-release.  If this file does not exist then  fall  back
              to  /usr/lib/os-release.   If  the  VARIABLE argument is not specified, then use PRETTY_NAME
              from the file or the system name (see \s).  This escape code allows to keep /etc/issue  dis‐
              tribution and release independent.  Note that \S{ANSI_COLOR} is converted to the real termi‐
              nal escape sequence.

```

Ideally the standard way of obtaining the OS name should be used

```
[user@localhost ~]$ lsb_release -i
Distributor ID:	Fedora

```

**Comment by craigbarnes** [comment]
> Ideally the standard way of obtaining the OS name should be used

LSB is pretty much a dead standard and `lsb_release` is usually not installed by default. Using `/etc/os-release` would be a better first choice.

Also, all this issue describes is the contents of some file on Fedora. It would be helpful to also describe how it actually relates to this codebase.

**Comment by bluedreamer** [comment]
I actually have pull request #54 that uses os-release. The issue is partly the build script printing out the platform and also making some decisions based on the OS name

**Comment by craigbarnes** [comment]
It seems to me like the maintainers of this project are still using it, but are now developing it as closed source. I have a private fork that I'm considering making open source, but it's 100% compatible with the original (far fewer flags and extra features).

**Comment by bluedreamer** [comment]
If you do - feel free to take my pull request if it applies - I like ohcount it is a cool tool. I was kinda lost who is maintaining this now. Shame if it went closed source

**Comment by craigbarnes** [comment]
They're obviously using it (or something like it) to power https://www.openhub.net/, which is why I'm guessing they just gave up on developing it in the open.

I've just pushed my fork to https://github.com/craigbarnes/tally if you're interested.

**Comment by PDegenPortnoy** [comment]
@bluedreamer, @craigbarnes I apologize for the delay in responding. Our small team continues to be responsible for Ohcount and use in creating the analytics that are display at https://www.openhub.net. We have returned our focus to Ohcount, which has been long neglected, and will be merging all viable pull requests in short order.

Thank you for your contribution and thoughts and please accept my apology for the delay.

**Comment by notalex** [comment]
The https://github.com/blackducksoftware/ohcount/pull/54 has been picked for the upcoming [version-4](https://github.com/blackducksoftware/ohcount/commits/version-4) branch. The reported issue will be fixed in the next release.
