### ISSUE TITLE
PHP being recognized as HTML

### ISSUE THREAD

**Issue by mtvan** [blackducksoftware/ohcount#52]
The first line of a php file (which also gives away it's php, is identified as html)

> `u:~/ohcount/bin$ ./ohcount -a test.php 

> html    lcode   <?php

> php     lcode   if ( !is_multisite() ) {`

**Comment by craigbarnes** [comment]
It's identified as HTML because *it is* HTML. Or more specifically, it's an SGML/XML processing instruction that's also recognised (and ignored) by HTML parsers.

**Comment by notalex** [comment]
Thanks for reporting this issue. It has been fixed in https://github.com/blackducksoftware/ohcount/pull/69. We will release a new ohcount version soon.
