### ISSUE TITLE
Currently Not Building

### ISSUE THREAD

**Issue by Feneric** [blackducksoftware/ohcount#62]
It's currently not building for me. Following the instructions as provided I'm seeing the following error message:

```
Building src/parser.c (will take a while)
src/parser.c:10:20: error: conflicting types for ‘ohcount_hash_parser_from_language’
 struct ParserMap * ohcount_hash_parser_from_language (register const char *str, register unsigned int len);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/parser.c:8:0:
parsers.gperf:170:1: note: previous definition of ‘ohcount_hash_parser_from_language’ was here
```

Digging in a little further, it's clear that there are some issues with the `gperf` step, as it produces the warning:

```
Found gperf, making headers...
1 input keys have identical hash values, examine output carefully...
```

and many of the generated files contain the error message:

```
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
```

By running the commands in `generate_headers` manually, it becomes clear that the specific file causing the identical hash value warning turns out to be `parsers.gperf`, and this would seem to tally with the build-killing error observed above.

**Comment by notalex** [comment]
Hi @Feneric, please provide the OS details to help debug this further. I could try it out in a container and share the results.

**Comment by xihuni** [comment]
> Hi @Feneric, please provide the OS details to help debug this further. I could try it out in a container and share the results.

I encounter the same problem on x64 version Ubuntu 18.04.1 LTS.

**Comment by notalex** [comment]
This issue has been fixed in the upcoming [version-4](https://github.com/blackducksoftware/ohcount/commits/version-4) branch.
