### ISSUE TITLE
modelica.rl:59:13: parse error

### ISSUE THREAD

**Issue by ryandesign** [blackducksoftware/ohcount#66]
Hello, I'm a developer with MacPorts, trying to update our ohcount package to your latest version, 3.1.1. I can't get it to build. Here's a partial build log:

```
Generating hash headers
Found gperf, making headers...
1 input keys have identical hash values, examine output carefully...
Found ragel, compiling...
Compiling actionscript.rl
Compiling ada.rl
Compiling ampl.rl
[...]
modelica.rl:59:13: parse error
[...]
Compiling xml.rl
Compiling xmlschema.rl
Compiling xslt.rl
Building src/parser.c (will take a while)
clang: warning: argument unused during compilation: '-L/opt/local/lib' [-Wunused-command-line-argument]
In file included from src/parser.c:8:
parsers.gperf:63:10: fatal error: '../parsers/modelica.h' file not found
#include "../parsers/modelica.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

I have ragel 7.0.0.11 installed.

**Comment by notalex** [comment]
Hi @ryandesign, I need to replicate the issue on my machine. I have tried packaging a macport for ohcount and I ran into missing distfile errors. It would be helpful if you could provide a list of commands to emulate this issue.

**Comment by notalex** [comment]
Hello @ryandesign, the modelica.rl parse error is fixed in the upcoming [version-4](https://github.com/blackducksoftware/ohcount/commits/version-4) branch. This branch is targeting the latest linux builds and is updated with all the patches we apply to the master. You may build from this branch.
