### ISSUE TITLE
Add support for dart lang

### ISSUE THREAD

**Issue by hpoul** [blackducksoftware/ohcount#74]
Would be nice if dart code would be identified correctly on https://openhub.net
Is the project still active? :-)

**Comment by notalex** [comment]
It is not much work to classify *.dart* files correctly. Inline dart code is harder to parse and we will need to work on that.
We can consider adding partial support(i.e. *.dart file detection) for now.
For inline dart we would be happy to accept any contributions.

**Comment by hpoul** [comment]
@notalex what do you mean with inline dart code? embedded inside HTML documents?
i guess that use case is dead anyway: https://dart.dev/web/dart-2#html-with-script-elements - I don't think anybody still considers adding direct dart support to any browser :-)

**Comment by notalex** [comment]
Yes, I did mean embedded dart inside HTML documents. Looks like we can do with simple file detection. Thanks for bringing this to light.
